### ISSUE TITLE
weird fortran error

### ISSUE THREAD

**Issue by dsclassen** [bl1231/bilbomd-worker#313]
I see this sometimes...

```
Error: OCI runtime error: crun: error executing hook `/usr/bin/hook_tool` (exit code: 1)
srun: error: nid001413: task 0: Exited with exit code 126
srun: Terminating StepId=26255441.1
srun: Job 26255441 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=26255441.2
At line 2415 of file /usr/local/src/charmm/build/cmake/psfres.F90 (unit = 1, file = 'fort.1')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7f123f314c5d in ???
#1  0x7f123f3157b9 in ???
#2  0x7f123f3163ff in ???
#3  0x7f123f584f2d in ???
#4  0x558d512917d0 in ???
#5  0x558d512699ac in ???
#6  0x558d50f673ec in ???
#7  0x558d50f64122 in ???
#8  0x558d50f62d6e in ???
#9  0x7f123eea11c9 in ???
#10  0x7f123eea128a in ???
#11  0x558d50f62d94 in ???
#12  0xffffffffffffffff in ???
srun: error: nid001413: task 0: Exited with exit code 2
srun: Terminating StepId=26255441.2
srun: Job 26255441 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=26255441.3
At line 223 of file /usr/local/src/charmm/build/cmake/psfres.F90 (unit = 12, file = 'fort.12')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7fe156cd0c5d in ???
#1  0x7fe156cd17b9 in ???
#2  0x7fe156cd23ff in ???
#3  0x7fe156f40f2d in ???
#4  0x555717b18464 in ???
#5  0x555717afff80 in ???
#6  0x5557177fe3ec in ???
#7  0x5557177fb122 in ???
#8  0x5557177f9d6e in ???
#9  0x7fe15685d1c9 in ???
#10  0x7fe15685d28a in ???
#11  0x5557177f9d94 in ???
#12  0xffffffffffffffff in ???
srun: error: nid001413: task 0: Exited with exit code 2
srun: Terminating StepId=26255441.3
srun: Job 26255441 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=26255441.4
srun: Job 26255441 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=26255441.5
At line 223 of file /usr/local/src/charmm/build/cmake/psfres.F90 (unit = 12, file = 'fort.12')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7f826a8c2c5d in ???
#1  0x7f826a8c37b9 in ???
#2  0x7f826a8c43ff in ???
#3  0x7f826ab32f2d in ???
#4  0x557b3e004464 in ???
#5  0x557b3dfebf80 in ???
#6  0x557b3dcea3ec in ???
#7  0x557b3dce7122 in ???
#8  0x557b3dce5d6e in ???
#9  0x7f826a44f1c9 in ???
#10  0x7f826a44f28a in ???
#11  0x557b3dce5d94 in ???
#12  0xffffffffffffffff in ???
srun: error: nid001413: task 0: Exited with exit code 2
srun: Terminating StepId=26255441.5
srun: Job 26255441 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=26255441.6
At line 223 of file /usr/local/src/charmm/build/cmake/psfres.F90 (unit = 12, file = 'fort.12')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7f714246cc5d in ???
#1  0x7f714246d7b9 in ???
#2  0x7f714246e3ff in ???
#3  0x7f71426dcf2d in ???
#4  0x56538bac8464 in ???
#5  0x56538baaff80 in ???
#6  0x56538b7ae3ec in ???
#7  0x56538b7ab122 in ???
#8  0x56538b7a9d6e in ???
#9  0x7f7141ff91c9 in ???
#10  0x7f7141ff928a in ???
#11  0x56538b7a9d94 in ???
#12  0xffffffffffffffff in ???
At line 187 of file /usr/local/src/charmm/build/cmake/parse.F90 (unit = 20, file = 'fort.20')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:

Could not print backtrace: /proc/self/exe: Transport endpoint is not connected

Program received signal SIGBUS: Access to an undefined portion of a memory object.

Backtrace for this error:
srun: error: nid001413: task 0: Exited with exit code 2
srun: Terminating StepId=26255441.6
srun: error: nid001413: task 0: Exited with exit code 135
srun: Terminating StepId=26255441.7
At line 223 of file /usr/local/src/charmm/build/cmake/psfres.F90 (unit = 12, file = 'fort.12')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7f319d192c5d in ???
#1  0x7f319d1937b9 in ???
#2  0x7f319d1943ff in ???
#3  0x7f319d402f2d in ???
#4  0x5563f5e84464 in ???
#5  0x5563f5e6bf80 in ???
#6  0x5563f5b6a3ec in ???
#7  0x5563f5b67122 in ???
#8  0x5563f5b65d6e in ???
#9  0x7f319cd1f1c9 in ???
#10  0x7f319cd1f28a in ???
#11  0x5563f5b65d94 in ???
#12  0xffffffffffffffff in ???
srun: error: nid001413: task 0: Exited with exit code 2
srun: Terminating StepId=26255441.8
At line 223 of file /usr/local/src/charmm/build/cmake/psfres.F90 (unit = 12, file = 'fort.12')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7f23991d2c5d in ???
#1  0x7f23991d37b9 in ???
#2  0x7f23991d43ff in ???
#3  0x7f2399442f2d in ???
#4  0x55e0c42b0464 in ???
#5  0x55e0c4297f80 in ???
#6  0x55e0c3f963ec in ???
#7  0x55e0c3f93122 in ???
#8  0x55e0c3f91d6e in ???
#9  0x7f2398d5f1c9 in ???
#10  0x7f2398d5f28a in ???
#11  0x55e0c3f91d94 in ???
#12  0xffffffffffffffff in ???
srun: error: nid001413: task 0: Exited with exit code 2
srun: Terminating StepId=26255441.9
At line 223 of file /usr/local/src/charmm/build/cmake/psfres.F90 (unit = 12, file = 'fort.12')
Fortran runtime error: Sequential READ or WRITE not allowed after EOF marker, possibly use REWIND or BACKSPACE

Error termination. Backtrace:
#0  0x7fba2d1a4c5d in ???
#1  0x7fba2d1a57b9 in ???
#2  0x7fba2d1a63ff in ???
#3  0x7fba2d414f2d in ???
#4  0x5613df7e2464 in ???
#5  0x5613df7c9f80 in ???
#6  0x5613df4c83ec in ???
#7  0x5613df4c5122 in ???
#8  0x5613df4c3d6e in ???
#9  0x7fba2cd311c9 in ???
#10  0x7fba2cd3128a in ???
#11  0x5613df4c3d94 in ???
#12  0xffffffffffffffff in ???
srun: error: nid001413: task 0: Exited with exit code 2
srun: Terminating StepId=26255441.10
srun: error: nid001413: task 0: Exited with exit code 5
srun: Terminating StepId=26255441.11
srun: Job 26255441 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=26255441.12
srun: Job 26255441 step creation temporarily disabled, retrying (Requested nodes are busy)
srun: Step created for StepId=26255441.13
./run_multifoxs.sh: line 8:     8 Aborted                 multi_foxs -o ../pro_dna_saxs.dat ./foxs_dat_files.txt &> multi_foxs.log
srun: error: nid001413: task 0: Exited with exit code 134
srun: Terminating StepId=26255441.13
```

**Comment by dsclassen** [comment]
can't reproduce reliably
